server:
  port: 8089
#  servlet:
#    encoding:
#      charset: utf-8
#      force: true
#  tomcat:
#    accesslog:
#      encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.142.190.42:3306/hisdata?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: shizi
    password: 123456
  jackson:
    date-format: yyyy-MM-dd hh:mm
  mvc:
    async:
      request-timeout: 80000

mybatis-plus:
  mapper-locations: classpath:mappers/*/*.xml
  config-location: classpath:mybatis-config.xml
# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  header: jwtAuth
  # Token前缀字符
  tokenPrefix: Security-c
  # 过期时间毫秒
  expire: 600000000
