server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/his-data?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: root
    password:
  jackson:
    date-format: yyyy-MM-dd