server:
  port: 8089
#  servlet:
#    encoding:
#      charset: utf-8
#      force: true
#  tomcat:
#    accesslog:
#      encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hisdata?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true
    username: root
    password:
  jackson:
    date-format: yyyy-MM-dd hh:mm

mybatis-plus:
  mapper-locations: classpath:mappers/*/*.xml
  config-location: classpath:mybatis-config.xml
